=== ttab/revisor/spec.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ttab/revisor/constraint-set",
  "$ref": "#/$defs/ConstraintSet",
  "$defs": {
    "BlockConstraint": {
      "properties": {
        "ref": {
          "type": "string"
        },
        "declares": {
          "$ref": "#/$defs/BlockSignature"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "match": {
          "additionalProperties": {
            "$ref": "#/$defs/StringConstraint"
          },
          "type": "object"
        },
        "count": {
          "type": "integer"
        },
        "maxCount": {
          "type": "integer"
        },
        "minCount": {
          "type": "integer"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/BlockConstraint"
          },
          "type": "array"
        },
        "meta": {
          "items": {
            "$ref": "#/$defs/BlockConstraint"
          },
          "type": "array"
        },
        "content": {
          "items": {
            "$ref": "#/$defs/BlockConstraint"
          },
          "type": "array"
        },
        "attributes": {
          "additionalProperties": {
            "$ref": "#/$defs/StringConstraint"
          },
          "type": "object"
        },
        "data": {
          "additionalProperties": {
            "$ref": "#/$defs/StringConstraint"
          },
          "type": "object"
        },
        "deprecated": {
          "$ref": "#/$defs/Deprecation"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "BlockDefinition": {
      "properties": {
        "id": {
          "type": "string"
        },
        "block": {
          "$ref": "#/$defs/BlockConstraint"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "id",
        "block"
      ]
    },
    "BlockSignature": {
      "properties": {
        "type": {
          "type": "string"
        },
        "rel": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ConstraintSet": {
      "properties": {
        "version": {
          "type": "integer"
        },
        "$schema": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "documents": {
          "items": {
            "$ref": "#/$defs/DocumentConstraint"
          },
          "type": "array"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/BlockDefinition"
          },
          "type": "array"
        },
        "meta": {
          "items": {
            "$ref": "#/$defs/BlockDefinition"
          },
          "type": "array"
        },
        "content": {
          "items": {
            "$ref": "#/$defs/BlockDefinition"
          },
          "type": "array"
        },
        "enums": {
          "items": {
            "$ref": "#/$defs/Enum"
          },
          "type": "array"
        },
        "htmlPolicies": {
          "items": {
            "$ref": "#/$defs/HTMLPolicy"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name"
      ]
    },
    "Deprecation": {
      "properties": {
        "label": {
          "type": "string"
        },
        "doc": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "label",
        "doc"
      ]
    },
    "DocumentConstraint": {
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "declares": {
          "type": "string"
        },
        "match": {
          "additionalProperties": {
            "$ref": "#/$defs/StringConstraint"
          },
          "type": "object"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/BlockConstraint"
          },
          "type": "array"
        },
        "meta": {
          "items": {
            "$ref": "#/$defs/BlockConstraint"
          },
          "type": "array"
        },
        "content": {
          "items": {
            "$ref": "#/$defs/BlockConstraint"
          },
          "type": "array"
        },
        "attributes": {
          "additionalProperties": {
            "$ref": "#/$defs/StringConstraint"
          },
          "type": "object"
        },
        "deprecated": {
          "$ref": "#/$defs/Deprecation"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Enum": {
      "properties": {
        "declare": {
          "type": "string"
        },
        "match": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "values": {
          "additionalProperties": {
            "$ref": "#/$defs/EnumConstraint"
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "values"
      ]
    },
    "EnumConstraint": {
      "properties": {
        "forbidden": {
          "type": "boolean"
        },
        "deprecated": {
          "$ref": "#/$defs/Deprecation"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Glob": {
      "properties": {},
      "additionalProperties": false,
      "type": "object"
    },
    "GlobList": {
      "items": {
        "$ref": "#/$defs/Glob"
      },
      "type": "array"
    },
    "HTMLElement": {
      "properties": {
        "attributes": {
          "additionalProperties": {
            "$ref": "#/$defs/StringConstraint"
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "HTMLPolicy": {
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "uses": {
          "type": "string"
        },
        "extends": {
          "type": "string"
        },
        "elements": {
          "additionalProperties": {
            "$ref": "#/$defs/HTMLElement"
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "elements"
      ]
    },
    "Regexp": {
      "properties": {},
      "additionalProperties": false,
      "type": "object"
    },
    "StringConstraint": {
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "optional": {
          "type": "boolean"
        },
        "allowEmpty": {
          "type": "boolean"
        },
        "const": {
          "type": "string"
        },
        "enum": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enumReference": {
          "type": "string"
        },
        "pattern": {
          "$ref": "#/$defs/Regexp"
        },
        "glob": {
          "$ref": "#/$defs/GlobList"
        },
        "format": {
          "type": "string"
        },
        "time": {
          "type": "string"
        },
        "geometry": {
          "type": "string"
        },
        "htmlPolicy": {
          "type": "string"
        },
        "deprecated": {
          "$ref": "#/$defs/Deprecation"
        },
        "labels": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "hints": {
          "additionalProperties": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== ttab/revisor/testdata/TestPrune/constraints/core.json
{
  "version": 1,
  "name": "core",
  "meta": [
    {
      "id": "core://note",
      "block": {
        "name": "Note",
        "description": "A public note",
        "declares": {"type":"core/note"},
        "attributes": {
          "role": {"const": "public"}
        },
        "data": {
          "text": {}
        }
      }
    },
    {
      "id": "core://description",
      "block": {
        "name": "Description",
        "description": "A public or internal description of the entity",
        "declares": {"type":"core/description", "role": "public"},
        "data": {
          "text": {}
        }
      }
    },
    {
      "id": "core://newsvalue",
      "block": {
        "name": "Newsvalue",
        "description": "The editorial newsvalue score and lifetime",
        "declares": {"type":"core/newsvalue"},
        "attributes": {
          "value": {
            "description": "The assigned newsvalue",
            "format": "int"
          }
        },
        "data": {
          "duration": {
            "description": "Duration in seconds, can represent the halving time for the score in a scoring algorithm.",
            "format":"int",
            "optional": true
          },
          "end": {
            "description": "The cut-off time that the document has no newsvalue",
            "format":"RFC3339",
            "optional":true
          }
        }
      }
    }
  ],
  "links": [
    {
      "id": "core://story",
      "block": {
        "name": "Story",
        "description": "An ongoing story that the document relates to",
        "declares": {"type": "core/story", "rel":"subject"},
        "attributes": {
          "uuid": {},
          "title": {"allowEmpty":true}
        }
      }
    },
    {
      "id": "core://section",
      "block": {
        "name": "Section",
        "description": "The editorial section the document belongs to",
        "declares": {"rel":"section", "type": "core/section"},
        "attributes": {
          "uuid": {},
          "title": {"allowEmpty":true}
        }
      }
    },
    {
      "id": "core://byline",
      "block": {
        "name": "Author byline",
        "description": "An author credited in the byline",
        "declares": {"type": "core/author", "rel":"author"},
        "attributes": {
          "uuid": {"optional":true},
          "title": {}
        },
        "data": {
          "firstName": {"optional":true},
          "lastName": {"optional":true}
        }
      }
    }
  ]
}

=== ttab/revisor/testdata/constraints/geo.json
{
  "version": 1,
  "name": "test",
  "enums": [
    {
      "declare": "core/place-uris",
      "values": {
        "place://old": {
          "deprecated": {
            "label": "old-place-uri",
            "doc": "Use new place URIs"
          }
        },
        "place://new": {}
      }
    }
  ],
  "documents": [
    {
      "name": "Place",
      "declares": "core/place",
      "deprecated": {
        "label": "place-document",
        "doc": "Stop sending these plz"
      },
      "attributes": {
        "title": {
          "allowEmpty": true,
          "deprecated": {
            "label": "genii-loci",
            "doc": "What places need names anyway?"
          }
        }
      },
      "meta": [
        {
          "declares": {"type":"core/place"},
          "attributes": {
            "role": {"optional":true},
            "uri": {
              "optional": true,
              "enumReference": "core/place-uris"
            }
          },
          "data": {
            "position": {
              "format": "wkt",
              "geometry": "point",
              "optional": true
            },
            "position_3d": {
              "format": "wkt",
              "geometry": "point-z",
              "optional": true,
              "deprecated": {
                "label": "3d-points",
                "doc": "Too ambitious, don't want"
              }
            },
            "area": {
              "format": "wkt",
              "geometry": "polygon",
              "optional": true
            },
            "road": {
              "format": "wkt",
              "geometry": "linestring",
              "optional": true
            }
          }
        },
        {
          "match": {
            "type": {"const":"core/place"},
            "role": {"const":"absurd"}
          },
          "attributes": {
            "role": {
              "allowEmpty": true,
              "deprecated": {
                "label": "absurdity",
                "doc": "Why did we ever think this was a good idea?"
              }
            }
          }
        }
      ]
    }
  ]
}

=== ttab/revisor/testdata/TestPrune/constraints/tt.json
{
  "version": 1,
  "name": "tt",
  "enums": [
    {
      "name": "Text roles",
      "description": "Customises allowed text roles for TT content.",
      "match": "core://text-roles",
      "values": {
        "heading-3": {"forbidden":true},
        "heading-4": {"forbidden":true},
        "vignette": {}
      }
    }
  ],
  "documents": [
    {
      "name": "Category",
      "description": "Extensions for category documents using IPTC mediatopics.",
      "match": {"type": {"const":"core/category"}},
      "attributes": {
        "uri": {
          "glob": ["iptc://mediatopic/*"]
        }
      },
      "links": [
        {
          "name": "IPTC mediatopic",
          "description": "Same-as link to the IPTC mediatopic identifier.",
          "declares": {"type":"iptc/mediatopic", "rel":"same-as"},
          "attributes": {
            "uri": {
              "glob": ["iptc://mediatopic/*"]
            }
          },
          "data": {
            "id": {"format":"int"}
          }
        }
      ]
    },
    {
      "name": "Flash",
      "description": "Extensions for flash news documents.",
      "match": {"type": {"const":"core/flash"}},
      "links": [
        {
          "name": "Section",
          "description": "Required section for flash documents.",
          "match": {
            "rel": {"const":"section"},
            "type": {"const":"core/section"}
          },
          "count": 1
        }
      ]
    },
    {
      "name": "Editorial info",
      "description": "Extensions for editorial info documents.",
      "match": {"type": {"const":"core/editorial-info"}},
      "meta": [
        {
          "ref": "tt://slugline",
          "count": 1
        }
      ],
      "links": [
        {
          "name": "Section",
          "description": "Required section for editorial info documents.",
          "match": {
            "rel": {"const":"section"},
            "type": {"const":"core/section"}
          },
          "count": 1
        },
        {
          "name": "Editorial-info type",
          "description": "Specifies the editorial-info type",
          "declares": {"type": "tt/editorial-info-type", "rel": "info-type"},
          "attributes": {
            "uuid": {}
          }
        }
      ],
      "content": [
        {"ref": "tt://visual"}
      ]
    },
    {
      "name": "Article",
      "description": "Extensions for article documents.",
      "match": {"type": {"const":"core/article"}},
      "links": [
        {
          "match": {
            "type":{"const":"core/section"},
            "rel":{"const":"section"}
          },
          "count": 1
        },
        {
          "name": "Subtype",
          "description": "Specifies the article subtype.",
          "declares": {"rel":"subtype"},
          "attributes": {
            "uri": {"glob": ["tt://subtype/*"]}
          }
        },
        {
          "name": "Content size",
          "description": "Specifies the content sizes we can use",
          "match": {
            "type": {"const":"core/content-size"}
          },
          "attributes": {
            "uri": {"enum":[
              "core://content-size/article/medium"
            ]}
          }
        }
      ],
      "content": [
        {"ref": "tt://visual"}
      ],
      "meta": [
        {
          "ref": "tt://slugline",
          "count": 1
        }
      ]
    }
  ],
  "meta": [
    {
      "id": "tt://slugline",
      "block": {
        "name": "Slugline",
        "description": "A short keyword label used for identifying the story.",
        "declares": {"type":"tt/slugline"},
        "attributes": {
          "value": {
            "labels": ["keyword", "prefix"],
            "hints": {"alias": ["slug"]}
          }
        }
      }
    }
  ],
  "content": [
    {
      "id": "tt://visual",
      "block": {
        "name": "TT visual element",
        "description": "This can be either a picture or a graphic",
        "declares": {"type":"tt/visual"},
        "data": {
          "caption": {"allowEmpty":true},
          "html_caption": {
            "format": "html",
            "allowEmpty": true,
            "optional": true
          }
        },
        "meta": [
          {"ref": "core://softcrop"}
        ],
        "links": [
          {
            "name": "Self-link",
            "description": "Self-link pointing to the picture or graphic resource.",
            "declares": {"rel":"self"},
            "count": 1,
            "attributes": {
              "uri": {},
              "url": {},
              "type": {
                "enum": ["tt/picture", "tt/graphic"]
              }
            },
            "data": {
              "credit": {"allowEmpty":true},
              "height": {"format":"int"},
              "width": {"format":"int"},
              "hiresScale": {
                "format": "float",
                "optional": true,
                "deprecated": {
                  "label": "hires-scale",
                  "doc": "Not supported anymore"
                }
              }
            }
          }
        ]
      }
    }
  ]
}

=== ttab/revisor/testdata/TestPrune/constraints/core-planning.json
{
  "version": 1,
  "name": "core-planning",
  "documents": [
    {
      "name": "Planning item",
      "description": "The planning item for an article or other deliverables",
      "declares": "core/planning-item",
      "links": [
        {
          "name": "Event",
          "description": "The event that this planning item is coverage of, if any",
          "declares": {
            "rel": "event",
            "type": "core/event"
          },
          "maxCount": 1,
          "attributes": {
            "uuid": {},
            "title": {}
          }
        },
        {
          "ref": "core://section",
          "count": 1
        },
        {
          "ref": "core://story"
        },
        {
          "name": "Category",
          "description": "The category of the planning item",
          "declares": {
            "rel": "category",
            "type": "core/category"
          },
          "attributes": {
            "uuid": {},
            "uri": { "optional": true },
            "title": {}
          }
        },
        {
          "name": "Place",
          "description": "The associated place for the planning item",
          "declares": {
            "rel": "place",
            "type": "core/place"
          },
          "attributes": {
            "uuid": {},
            "title": {}
          }
        }
      ],
      "meta": [
        {
          "ref": "core://description"
        },
        {
          "ref": "core://newsvalue",
          "count": 1
        },
        {
          "name": "Planning metadata",
          "description": "Main metadata block for the planning item",
          "declares": {
            "type": "core/planning-item"
          },
          "count": 1,
          "data": {
            "start_date": {
              "description": "The start date for the planning item",
              "time": "2006-01-02"
            },
            "end_date": {
              "description": "The end date for the planning item",
              "time": "2006-01-02"
            },
            "date_tz": {
              "description": "The timezone the date is in",
              "optional": true
            }
          }
        },
        {
          "name": "Assignment",
          "description": "An assignment associated with the planning item",
          "declares": {
            "type": "core/assignment"
          },
          "attributes": {
            "id": {
              "description": "A unique identifier for the assignment",
              "format": "uuid"
            },
            "title": { "allowEmpty": true }
          },
          "data": {
            "full_day": {
              "description": "Whether this is assignment is for a date rather than a specific time.",
              "format": "bool",
              "optional": true
            },
            "start": {
              "description": "When the assignment should be carried out",
              "format": "RFC3339",
              "optional": true
            },
            "end": {
              "description": "When work on the assignment ends.",
              "format": "RFC3339",
              "optional": true
            },
            "start_date": {
              "description": "The start date for the assignment",
              "time": "2006-01-02",
              "optional": true
            },
            "end_date": {
              "description": "The end date for the assignment",
              "time": "2006-01-02",
              "optional": true
            },
            "date_tz": {
              "description": "The timezone the date is in",
              "optional": true
            },
            "publish": {
              "description": "The exact time the deliverables will be published",
              "format": "RFC3339",
              "optional": true
            },
            "public": {
              "description": "Require the assignment to be public",
              "format": "bool",
              "const": "true"
            },
            "publish_slot": {
              "description": "The approximate timeslot the deliverables should be published.",
              "format": "int",
              "optional": true
            }
          },
          "meta": [
            {
              "name": "Assignment type",
              "description": "Describes what kind of assignment this is",
              "declares": {
                "type": "core/assignment-type"
              },
              "minCount": 1,
              "attributes": {
                "value": {
                  "enumReference": "core://assignment-types"
                }
              }
            }
          ],
          "links": [
            {
              "name": "Section",
              "description": "Section associated with the assignment",
              "declares": {
                "type": "core/section",
                "rel": "section"
              },
              "attributes": {
                "uuid": {},
                "title": {}
              }
            },
            {
              "name": "Location",
              "description": "Geographic location for the assignment",
              "declares": {
                "type": "core/geo-point",
                "rel": "location"
              },
              "attributes": {
                "title": {}
              },
              "data": {
                "country": { "optional": true },
                "locality": { "optional": true },
                "name": { "optional": true },
                "extraInfo": { "optional": true },
                "geometry": {}
              }
            },
            {
              "name": "Deliverable",
              "description": "A deliverable of the planning item",
              "declares": {
                "rel": "deliverable"
              },
              "attributes": {
                "uuid": {},
                "type": {}
              }
            }
          ]
        }
      ]
    }
  ],
  "enums": [
    {
      "declare": "core://assignment-types",
      "values": {
        "text": {},
        "picture": {},
        "video": {},
        "graphic": {},
        "flash": {},
        "editorial-info": {}
      }
    }
  ]
}
